FROM node:20-alpine AS build

WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm ci

# Copy the rest of the code
COPY . .

# Build the application using NX
RUN npx nx build web --configuration=development

# Production stage
FROM nginx:alpine AS runtime

# Copy the built files from the build stage to the nginx directory
COPY --from=build /app/dist/apps/web /usr/share/nginx/html

# Add custom NGINX configuration for development
COPY --from=build /app/apps/web/nginx.dev.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"] 